import { NextRequest, NextResponse } from 'next/server'
import { getServerSession }  from 'next-auth'
import { authOptions }       from '@/lib/auth'
import { prisma }            from '@/lib/prisma'

function markdownToHtml(md: string): string {
  return md
    .replace(/^# (.+)$/gm,  '<h1 style="font-size:18pt;font-weight:bold;color:#1a3a6e;margin:16px 0 8px">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:14pt;font-weight:bold;color:#1a3a6e;margin:14px 0 6px;border-bottom:1px solid #ccc;padding-bottom:4px">$1</h2>')
    .replace(/^### (.+)$/gm,'<h3 style="font-size:12pt;font-weight:bold;color:#333;margin:10px 0 4px">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,    '<em>$1</em>')
    .replace(/^- (.+)$/gm,   '<li style="margin:3px 0">$1</li>')
    .replace(/(<li.*?<\/li>\n?)+/g, m => `<ul style="margin:8px 0;padding-left:20px">${m}</ul>`)
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #ccc;margin:16px 0">')
    .replace(/\n\n/g, '</p><p style="margin:8px 0">')
    .replace(/\n/g, '<br>')
}

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) return new NextResponse('Unauthorized', { status: 401 })
  const format = req.nextUrl.searchParams.get('format') ?? 'pdf'
  const draft = await prisma.aiDraft.findUnique({ where: { id: params.id }, include: { case: { select: { userId: true, organizationId: true, applicantName: true } } } })
  if (!draft) return new NextResponse('Not found', { status: 404 })
  if (draft.userId !== session.user.id && draft.case.userId !== session.user.id) return new NextResponse('Forbidden', { status: 403 })
  const content = draft.userEdits || draft.content
  const slug    = `${draft.draftType}_${draft.case.applicantName}`.replace(/[^a-z0-9]/gi,'_').toLowerCase()

  if (format === 'docx') {
    try {
      // @ts-ignore
      const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx')
      const lines = content.split('\n')
      const children: any[] = []
      for (const line of lines) {
        const trimmed = line.trim()
        if (!trimmed) { children.push(new Paragraph({ text: '' })); continue }
        if (trimmed.startsWith('# '))        { children.push(new Paragraph({ text: trimmed.slice(2), heading: HeadingLevel.HEADING_1 })); continue }
        if (trimmed.startsWith('## '))       { children.push(new Paragraph({ text: trimmed.slice(3), heading: HeadingLevel.HEADING_2 })); continue }
        if (trimmed.startsWith('### '))      { children.push(new Paragraph({ text: trimmed.slice(4), heading: HeadingLevel.HEADING_3 })); continue }
        if (trimmed.startsWith('- '))        { children.push(new Paragraph({ text: trimmed.slice(2), bullet: { level: 0 } })); continue }
        if (trimmed === '---')               { children.push(new Paragraph({ text: '─'.repeat(60) })); continue }
        // Bold handling
        const parts = trimmed.split(/\*\*(.+?)\*\*/)
        const runs  = parts.map((p: string, i: number) => new TextRun({ text: p, bold: i % 2 === 1, size: 22 }))
        children.push(new Paragraph({ children: runs }))
      }
      const doc    = new Document({ sections: [{ children }] })
      const buffer = await Packer.toBuffer(doc)
      await prisma.aiDraft.update({ where: { id: params.id }, data: { exportedAt: new Date(), exportFormat: 'docx', status: 'exported' } })
      return new NextResponse(new Uint8Array(buffer), {
        headers: { 'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'Content-Disposition': `attachment; filename="${slug}.docx"` },
      })
    } catch (e) { console.error('docx error', e) }
  }

  // HTML/PDF
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:'Times New Roman',serif;font-size:11pt;color:#111;margin:0;line-height:1.5}
    .page{max-width:750px;margin:0 auto;padding:40px}
    .header{text-align:center;border-bottom:2px solid #1a3a6e;padding-bottom:12px;margin-bottom:24px}
    .watermark{color:#cc0000;font-size:9pt;text-align:center;margin-bottom:16px;font-weight:bold}
    .footer{margin-top:40px;font-size:8pt;color:#888;border-top:1px solid #ccc;padding-top:8px}
    @media print{body{margin:.75in}}
  </style></head><body><div class="page">
  <div class="watermark">⚠️ DRAFT — FOR ATTORNEY REVIEW ONLY — NOT FOR SUBMISSION</div>
  <div class="header"><div style="color:#666;font-size:9pt">U.S. IMMIGRATION LAW — CONFIDENTIAL</div><div style="font-size:10pt;margin-top:4px">Generated by ImmigAI | ${new Date().toLocaleDateString()}</div></div>
  <p style="margin:8px 0">${markdownToHtml(content)}</p>
  <div class="footer">DRAFT ONLY — All exhibits and dates require verification before official submission. This document was generated by AI and must be reviewed and edited by a licensed immigration attorney prior to use.</div>
  </div></body></html>`

  await prisma.aiDraft.update({ where: { id: params.id }, data: { exportedAt: new Date(), exportFormat: 'pdf', status: 'exported' } })
  return new NextResponse(html, { headers: { 'Content-Type': 'text/html', 'Content-Disposition': `inline; filename="${slug}.html"` } })
}
