import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { getFormSchema } from '@/lib/form-schemas'

async function buildFormHTML(formType: string, fieldData: Record<string,any>, caseData: any): Promise<string> {
  const schema = getFormSchema(formType)
  if (!schema) return '<p>Unknown form type</p>'

  const sections = schema.sections.map(section => {
    const rows = section.fields
      .filter(f => !['checkbox'].includes(f.type) || fieldData[f.id])
      .map(f => {
        const val = fieldData[f.id]
        if (val === undefined || val === null || val === '') return ''
        const display = typeof val === 'boolean' ? (val ? '☑ Yes' : '☐ No') : String(val)
        return `<tr><td class="label">${f.label}</td><td class="value">${display}</td></tr>`
      })
      .filter(Boolean)
      .join('\n')

    if (!rows) return ''

    return `
      <div class="section">
        <h3>${section.title}</h3>
        ${section.subtitle ? `<p class="subtitle">${section.subtitle}</p>` : ''}
        <table>${rows}</table>
      </div>`
  }).filter(Boolean).join('\n')

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Times New Roman', serif; font-size: 11pt; color: #000; margin: 0; }
  .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 12px; margin-bottom: 20px; }
  .header h1 { font-size: 16pt; margin: 0 0 4px; }
  .header h2 { font-size: 13pt; font-weight: normal; margin: 0 0 4px; }
  .header .meta { font-size: 9pt; color: #555; }
  .section { margin-bottom: 20px; page-break-inside: avoid; }
  .section h3 { font-size: 12pt; font-weight: bold; border-bottom: 1px solid #999; padding-bottom: 4px; margin-bottom: 8px; color: #1a3a6e; }
  .section .subtitle { font-size: 9pt; color: #555; margin: -4px 0 8px; font-style: italic; }
  table { width: 100%; border-collapse: collapse; }
  tr { border-bottom: 1px solid #eee; }
  td { padding: 5px 8px; vertical-align: top; }
  .label { width: 42%; font-weight: 600; font-size: 10pt; color: #333; }
  .value { font-size: 10pt; }
  .footer { margin-top: 30px; font-size: 9pt; color: #777; border-top: 1px solid #ccc; padding-top: 10px; }
  @media print { body { margin: 0.75in; } }
</style>
</head>
<body>
  <div class="header">
    <div class="meta">U.S. Citizenship and Immigration Services</div>
    <h1>${schema.formType}</h1>
    <h2>${schema.title}</h2>
    <div class="meta">
      Case: ${caseData?.applicantName ?? 'N/A'} &bull;
      Generated: ${new Date().toLocaleDateString('en-US', {year:'numeric',month:'long',day:'numeric'})} &bull;
      Status: DRAFT — FOR REVIEW ONLY
    </div>
  </div>
  ${sections}
  <div class="footer">
    <strong>IMPORTANT:</strong> This is a working draft generated by ImmigAI for attorney review.
    This document has not been reviewed or submitted to USCIS.
    Always verify completeness and accuracy before official submission.
    USCIS Form: <a href="${schema.uscisUrl ?? '#'}">${schema.uscisUrl ?? 'See USCIS.gov'}</a>
  </div>
</body>
</html>`
}

async function buildDocxXml(formType: string, fieldData: Record<string,any>, caseData: any): Promise<Buffer> {
  // Dynamically import docx to avoid SSR issues
  // @ts-ignore
    const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, WidthType, AlignmentType } = await import('docx')

  const schema = getFormSchema(formType)
  if (!schema) throw new Error('Unknown form type')

  const children: any[] = []

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'U.S. Citizenship and Immigration Services', size: 18, color: '444444' })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: `${schema.formType} — ${schema.title}`, bold: true, size: 28, color: '1a3a6e' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: `Case: ${caseData?.applicantName ?? 'N/A'} | Generated: ${new Date().toLocaleDateString()} | DRAFT — FOR REVIEW ONLY`,
        size: 16, color: '888888', italics: true,
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  )

  // Sections
  for (const section of schema.sections) {
    const filledFields = section.fields.filter(f => {
      const v = fieldData[f.id]
      return v !== undefined && v !== null && v !== '' && v !== false
    })
    if (filledFields.length === 0) continue

    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 120 },
      })
    )

    const rows = filledFields.map(f => {
      const val = fieldData[f.id]
      const display = typeof val === 'boolean' ? (val ? '☑ Yes' : '☐ No') : String(val)
      return new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: f.label, bold: true, size: 20 })] })],
            width: { size: 40, type: WidthType.PERCENTAGE },
            borders: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' }, top: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: display, size: 20 })] })],
            width: { size: 60, type: WidthType.PERCENTAGE },
            borders: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' }, top: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
          }),
        ],
      })
    })

    children.push(
      new Table({
        rows,
        width: { size: 100, type: WidthType.PERCENTAGE },
      })
    )
  }

  // Footer
  children.push(
    new Paragraph({
      children: [new TextRun({
        text: 'IMPORTANT: This is a working draft generated by ImmigAI for attorney review. This document has not been submitted to USCIS. Always verify before official submission.',
        size: 16, italics: true, color: '888888',
      })],
      spacing: { before: 600 },
    })
  )

  const doc = new Document({ sections: [{ children }] })
  return Packer.toBuffer(doc)
}

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) return new NextResponse('Unauthorized', { status: 401 })

    const format = req.nextUrl.searchParams.get('format') ?? 'pdf'

    const form = await prisma.form.findUnique({
      where: { id: params.id },
      include: { case: { select: { userId: true, organizationId: true, applicantName: true } } },
    })
    if (!form) return new NextResponse('Not found', { status: 404 })

    // Auth
    const ownCase = form.case.userId === session.user.id
    const ownForm = form.userId === session.user.id
    if (!ownCase && !ownForm) {
      const u = await prisma.user.findUnique({ where: { id: session.user.id }, select: { role: true, organizationId: true } })
      if (u?.role !== 'admin' || u.organizationId !== form.case.organizationId) {
        return new NextResponse('Forbidden', { status: 403 })
      }
    }

    const fieldData: Record<string, any> = JSON.parse(form.fieldData)
    const caseData = form.case
    const applicantSlug = caseData.applicantName.replace(/[^a-z0-9]/gi, '_').toLowerCase()

    if (format === 'docx') {
      const buffer = await buildDocxXml(form.formType, fieldData, caseData)
      await prisma.form.update({
        where: { id: params.id },
        data: { exportedAt: new Date(), exportFormat: 'docx' },
      })
      return new NextResponse(new Uint8Array(buffer), {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="${form.formType}_${applicantSlug}.docx"`,
        },
      })
    }

    // Default: return HTML for client-side PDF printing
    const html = await buildFormHTML(form.formType, fieldData, caseData)
    await prisma.form.update({
      where: { id: params.id },
      data: { exportedAt: new Date(), exportFormat: 'pdf' },
    })
    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="${form.formType}_${applicantSlug}.html"`,
      },
    })
  } catch (err: any) {
    console.error('Export error:', err)
    return new NextResponse(err.message ?? 'Export failed', { status: 500 })
  }
}
