export const COUNTRIES: { value: string; label: string }[] = [
  { value: 'US', label: 'United States' },
  { value: 'AF', label: 'Afghanistan' }, { value: 'AL', label: 'Albania' },
  { value: 'DZ', label: 'Algeria' }, { value: 'AR', label: 'Argentina' },
  { value: 'AU', label: 'Australia' }, { value: 'AT', label: 'Austria' },
  { value: 'BD', label: 'Bangladesh' }, { value: 'BE', label: 'Belgium' },
  { value: 'BR', label: 'Brazil' }, { value: 'CA', label: 'Canada' },
  { value: 'CL', label: 'Chile' }, { value: 'CN', label: 'China' },
  { value: 'CO', label: 'Colombia' }, { value: 'HR', label: 'Croatia' },
  { value: 'CZ', label: 'Czech Republic' }, { value: 'DK', label: 'Denmark' },
  { value: 'EG', label: 'Egypt' }, { value: 'ET', label: 'Ethiopia' },
  { value: 'FI', label: 'Finland' }, { value: 'FR', label: 'France' },
  { value: 'DE', label: 'Germany' }, { value: 'GH', label: 'Ghana' },
  { value: 'GR', label: 'Greece' }, { value: 'GT', label: 'Guatemala' },
  { value: 'HN', label: 'Honduras' }, { value: 'HK', label: 'Hong Kong' },
  { value: 'HU', label: 'Hungary' }, { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' }, { value: 'IR', label: 'Iran' },
  { value: 'IQ', label: 'Iraq' }, { value: 'IE', label: 'Ireland' },
  { value: 'IL', label: 'Israel' }, { value: 'IT', label: 'Italy' },
  { value: 'JM', label: 'Jamaica' }, { value: 'JP', label: 'Japan' },
  { value: 'JO', label: 'Jordan' }, { value: 'KE', label: 'Kenya' },
  { value: 'KR', label: 'South Korea' }, { value: 'KW', label: 'Kuwait' },
  { value: 'LB', label: 'Lebanon' }, { value: 'MX', label: 'Mexico' },
  { value: 'MA', label: 'Morocco' }, { value: 'NL', label: 'Netherlands' },
  { value: 'NZ', label: 'New Zealand' }, { value: 'NG', label: 'Nigeria' },
  { value: 'NO', label: 'Norway' }, { value: 'PK', label: 'Pakistan' },
  { value: 'PE', label: 'Peru' }, { value: 'PH', label: 'Philippines' },
  { value: 'PL', label: 'Poland' }, { value: 'PT', label: 'Portugal' },
  { value: 'RO', label: 'Romania' }, { value: 'RU', label: 'Russia' },
  { value: 'SA', label: 'Saudi Arabia' }, { value: 'SN', label: 'Senegal' },
  { value: 'ZA', label: 'South Africa' }, { value: 'ES', label: 'Spain' },
  { value: 'LK', label: 'Sri Lanka' }, { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' }, { value: 'TW', label: 'Taiwan' },
  { value: 'TZ', label: 'Tanzania' }, { value: 'TH', label: 'Thailand' },
  { value: 'TR', label: 'Turkey' }, { value: 'UA', label: 'Ukraine' },
  { value: 'GB', label: 'United Kingdom' }, { value: 'UZ', label: 'Uzbekistan' },
  { value: 'VE', label: 'Venezuela' }, { value: 'VN', label: 'Vietnam' },
  { value: 'YE', label: 'Yemen' }, { value: 'ZW', label: 'Zimbabwe' },
]

export const US_STATES: { value: string; label: string }[] = [
  {value:'AL',label:'Alabama'},{value:'AK',label:'Alaska'},{value:'AZ',label:'Arizona'},
  {value:'AR',label:'Arkansas'},{value:'CA',label:'California'},{value:'CO',label:'Colorado'},
  {value:'CT',label:'Connecticut'},{value:'DE',label:'Delaware'},{value:'FL',label:'Florida'},
  {value:'GA',label:'Georgia'},{value:'HI',label:'Hawaii'},{value:'ID',label:'Idaho'},
  {value:'IL',label:'Illinois'},{value:'IN',label:'Indiana'},{value:'IA',label:'Iowa'},
  {value:'KS',label:'Kansas'},{value:'KY',label:'Kentucky'},{value:'LA',label:'Louisiana'},
  {value:'ME',label:'Maine'},{value:'MD',label:'Maryland'},{value:'MA',label:'Massachusetts'},
  {value:'MI',label:'Michigan'},{value:'MN',label:'Minnesota'},{value:'MS',label:'Mississippi'},
  {value:'MO',label:'Missouri'},{value:'MT',label:'Montana'},{value:'NE',label:'Nebraska'},
  {value:'NV',label:'Nevada'},{value:'NH',label:'New Hampshire'},{value:'NJ',label:'New Jersey'},
  {value:'NM',label:'New Mexico'},{value:'NY',label:'New York'},{value:'NC',label:'North Carolina'},
  {value:'ND',label:'North Dakota'},{value:'OH',label:'Ohio'},{value:'OK',label:'Oklahoma'},
  {value:'OR',label:'Oregon'},{value:'PA',label:'Pennsylvania'},{value:'RI',label:'Rhode Island'},
  {value:'SC',label:'South Carolina'},{value:'SD',label:'South Dakota'},{value:'TN',label:'Tennessee'},
  {value:'TX',label:'Texas'},{value:'UT',label:'Utah'},{value:'VT',label:'Vermont'},
  {value:'VA',label:'Virginia'},{value:'WA',label:'Washington'},{value:'WV',label:'West Virginia'},
  {value:'WI',label:'Wisconsin'},{value:'WY',label:'Wyoming'},{value:'DC',label:'D.C.'},
]
